name: 'Terraform Deployment'

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  checkov:
    name: 'Checkov'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          output_format: sarif
          output_file_path: reports/checkov-results.sarif

  tflint:
    name: 'Tflint'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup TFLint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Install Terraform plugins
        run: tflint --init
      - name: Lint Terraform files
        run: tflint
        
  create-pull-request:
    name: 'create-pull-request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: 'Create pull request'
          branch: main
          title: 'Pull Request Title'
          body: 'Pull Request Body'

      - name: Request Review
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: 'Please review this pull request'
          token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
