name: 'Terraform Deployment'

on:
  push:
    branches:
      - test

permissions:
  contents: read

jobs:
  checkov:
    name: 'Checkov'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          output_format: sarif
          output_file_path: reports/checkov-results.sarif

  tflint:
    name: 'Tflint'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup TFLint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Install Terraform plugins
        run: tflint --init
      - name: Lint Terraform files
        run: tflint
        
## pull steps    
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Script
        uses: actions/github-script@v6
        with:
          script: |
            git branch -a
      
