name: 'Terraform Deployment'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  checkov:
    name: 'Checkov'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          output_format: sarif
          output_file_path: reports/checkov-results.sarif

  tflint:
    name: 'Tflint'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup TFLint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - name: Install Terraform plugins
        run: tflint --init
      - name: Lint Terraform files
        run: tflint

  pull-request-review:
    name: 'pull-request-review'
    runs-on: ubuntu-latest

    steps:
      - name: Add Pull Request Reviewer
        uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with: 
          reviewers: "sidlakhani94"
          token: ${{ secrets.PAT }}
